version: '2'

services:
  web:
    container_name: web
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./conf/nginx_vhost:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
  php:
    env_file: .env
    container_name: php
    build:
      context: ./services/php
    volumes:
      - ./build/public:/www/public
      - ./build/craft:/www/craft
  db:
    env_file: .env
    container_name: db
    image: mysql:5.6
    volumes:
      - ./mysql_data:/var/lib/mysql
